POST http://localhost:3000/user/create
Content-Type: application/json 

{
    "_id": "1",
    "role": "member",
    "name": "John Doe",
    "age": 12.1,
    "enrollment_date": "2012-04-23T18:25:43.511Z",
    "fines": [
        {
            "total_cost": 10.1,
            "daily_rate": 1.1,
            "book_id": "1234"
        }
    ],
    "books": [
        {
            "book_id": "1234",
            "title": "A Very Interesting Book",
            "author": "George Greggory"
        }
    ],
    "email": "me@site.com"
}
###

POST http://localhost:3000/user/delete
Content-Type: application/json 

{
    "id": "1"
}
###

GET http://localhost:3000/user/1
###